"""Tests for the RFC agent (plan §10.6)."""

from __future__ import annotations

from unittest.mock import AsyncMock

import pytest

from ash.agents.rfc import RFCAgent
from ash.config.settings import AgentPolicy, ProjectConfig, Settings
from ash.graph.state import WorkflowState
from ash.integrations.base import RawIssue
from ash.schemas import RFCDocument


@pytest.fixture(autouse=True)
def _no_db(monkeypatch):
    """Force the DB-unavailable fallback so policy resolves from the mocked YAML config
    alone — these are unit tests of agent logic, not the DB merge (covered elsewhere)."""

    def _raise() -> None:
        raise RuntimeError("no DB in unit test")

    monkeypatch.setattr("ash.db.base.get_sessionmaker", _raise)


def _state(raw_issue: RawIssue | None = None) -> WorkflowState:
    state = WorkflowState(run_id="r1", project="plane", item_id="42")
    if raw_issue is not None:
        state.raw_issue = raw_issue
    return state


def _project_auto() -> ProjectConfig:
    return ProjectConfig(name="plane", agents={"rfc": AgentPolicy(trigger="auto")})


# ── skip cases ────────────────────────────────────────────────────────────────


async def test_rfc_skips_when_manual_trigger_declined(monkeypatch):
    """RFC (manual, the default) skips when the human declines the trigger (resume != 'run')."""
    cfg = ProjectConfig(name="plane", agents={"rfc": AgentPolicy(trigger="manual")})
    monkeypatch.setattr("ash.agents.base.load_project", lambda n: cfg)
    # override the conftest auto-trigger: the human chose to Skip rather than Trigger
    monkeypatch.setattr("ash.agents.base.interrupt", lambda _v=None: "skip")
    update = await RFCAgent(Settings()).run(_state(RawIssue(id="1", title="t", body="b")))
    assert "skipped" in update["rfc"]["note"]


async def test_rfc_runs_when_manually_triggered(monkeypatch):
    """RFC (manual) generates the doc when the human clicks Trigger (conftest interrupt → 'run')."""
    cfg = ProjectConfig(name="plane", agents={"rfc": AgentPolicy(trigger="manual")})
    monkeypatch.setattr("ash.agents.base.load_project", lambda n: cfg)
    doc = RFCDocument(
        title="RFC-001", background="b", problem_statement="p", proposed_solution="s"
    )
    agent = RFCAgent(Settings())
    agent._generate = AsyncMock(return_value=doc)  # type: ignore[method-assign]
    update = await agent.run(_state(RawIssue(id="1", title="t", body="b")))
    assert update["rfc"]["doc"] is not None
    assert "RFC-001" in update["rfc"]["doc"]


async def test_rfc_skips_when_no_brief(monkeypatch):
    """RFC skips when there's nothing to generate a document from."""
    monkeypatch.setattr("ash.agents.base.load_project", lambda n: _project_auto())
    state = WorkflowState(run_id="r1", project="plane", item_id="42")
    # no raw_issue and no pm spec → brief() returns ""
    update = await RFCAgent(Settings()).run(state)
    assert "skipped" in update["rfc"]["note"]


async def test_rfc_skips_when_disabled(monkeypatch):
    """RFC skips when enabled=False."""
    cfg = ProjectConfig(
        name="plane", agents={"rfc": AgentPolicy(trigger="auto", enabled=False)}
    )
    monkeypatch.setattr("ash.agents.base.load_project", lambda n: cfg)
    state = _state(RawIssue(id="1", title="t", body="b"))
    update = await RFCAgent(Settings()).run(state)
    assert "skipped" in update["rfc"]["note"]


# ── happy path ────────────────────────────────────────────────────────────────


async def test_rfc_generates_document(monkeypatch):
    """When enabled and a brief exists, RFC generates and returns a Markdown doc."""
    monkeypatch.setattr("ash.agents.base.load_project", lambda n: _project_auto())

    doc = RFCDocument(
        title="RFC-001: Add health endpoint",
        background="We need health checks.",
        problem_statement="No health endpoint exists.",
        proposed_solution="Add GET /health returning 200.",
        acceptance_criteria=["GET /health returns 200"],
    )
    state = _state(RawIssue(id="42", title="add health", body="GET /health → 200"))
    agent = RFCAgent(Settings())
    agent._generate = AsyncMock(return_value=doc)  # type: ignore[method-assign]

    update = await agent.run(state)

    assert update["rfc"]["doc"] is not None
    assert "RFC-001" in update["rfc"]["doc"]
    assert "GET /health" in update["rfc"]["doc"]
    assert "Generated by the ASH RFC agent" in update["rfc"]["doc"]


# ── RFCDocument.to_markdown ───────────────────────────────────────────────────


def test_rfc_document_to_markdown_full():
    doc = RFCDocument(
        title="RFC-002: Rate limiting",
        background="APIs are being hammered.",
        problem_statement="No rate limits exist.",
        proposed_solution="Add token-bucket middleware.",
        alternatives_considered="Leaky bucket — rejected because complex.",
        acceptance_criteria=["429 returned after limit", "headers expose remaining"],
        open_questions=["Which storage backend?"],
    )
    md = doc.to_markdown()
    assert "# RFC-002: Rate limiting" in md
    assert "## Background" in md
    assert "## Alternatives Considered" in md
    assert "## Acceptance Criteria" in md
    assert "- 429 returned after limit" in md
    assert "## Open Questions" in md
    assert "- Which storage backend?" in md
    assert "_Generated by the ASH RFC agent._" in md


def test_rfc_document_to_markdown_minimal():
    """Sections with no content are omitted."""
    doc = RFCDocument(
        title="RFC-003: Simple",
        background="bg",
        problem_statement="ps",
        proposed_solution="sol",
    )
    md = doc.to_markdown()
    assert "## Alternatives Considered" not in md
    assert "## Acceptance Criteria" not in md
    assert "## Open Questions" not in md
