"""Dev / Coding agent (write) — turns the plan into real file edits, commits, pushes, opens a PR.

Returns FULL file contents (not diffs — more reliable for smaller models) for a bounded set of
files, applies them inside the isolated worktree, and opens a draft fork PR that carries CODE
(plan §4c). The merge gate is consulted via `ApprovalGate`. The worktree is cleaned up afterward
(while Reviewer/Fixer are stubs); when they become real, cleanup moves to the merge node.
"""

from __future__ import annotations

import asyncio
from pathlib import Path
from typing import Any

from ash.agents.base import BaseAgent
from ash.clients import code_intel
from ash.clients.git_repo import RepoWorkspace
from ash.clients.pr import create_pr
from ash.config.settings import load_project
from ash.gates import ApprovalGate
from ash.graph.state import WorkflowState
from ash.schemas import CodeChange, EditAction, ImplementationPlan

_SYSTEM = """You are a senior engineer implementing a planned change. You are given the spec, the \
implementation plan, and the current contents of the relevant files. Produce the MINIMAL set of \
file edits that implements the plan.

Rules:
- Return the FULL new content for each file you create or modify (never a diff/patch).
- Keep changes small and focused; match the surrounding code style.
- Only touch files that are necessary. Prefer modifying listed files over inventing new ones.
- If you cannot safely implement something, make the smallest correct partial change and note it."""

_MAX_FILES = 4


class CodingAgent(BaseAgent):
    name = "coding"

    async def run(self, state: WorkflowState) -> dict[str, Any]:
        plan = state.research.plan
        brief = state.brief()
        wt = state.research.worktree_path
        branch = state.research.branch
        if plan is None or not brief or wt is None or branch is None:
            return {"coding": {"note": "skipped: no plan/worktree from research"}}

        project = load_project(state.project)
        if project.work is None:
            return {"coding": {"note": "skipped: project has no work target"}}
        work = project.work
        wt_path = Path(wt)
        ws = RepoWorkspace(work, project.runtime_dir / "worktrees")
        try:
            change = await self._code(wt_path, brief, plan)
            if not change.edits:
                return {"coding": {"change": change, "note": "no edits produced; needs human"}}

            written = await asyncio.to_thread(_apply_change, wt_path, change)
            msg = f"agent: implement issue #{state.item_id} — {state.issue_title}"
            await asyncio.to_thread(ws.commit_all, wt_path, msg)
            await asyncio.to_thread(ws.push_branch, wt_path, branch)

            body = (
                f"Implements item {state.item_id} — {state.issue_url}\n\n"
                f"{change.summary}\n\n"
                f"**Files changed:** {', '.join(written)}\n\n"
                f"**Tests:** {change.tests_note or 'n/a'}\n\n"
                f"_Spec on board: `{state.pm.board_ref}`. Generated by the ASH build team._"
            )
            pr_url = await asyncio.to_thread(
                create_pr,
                target_repo=work.target_repo,
                base=work.base_branch,
                head=branch,
                title=f"[agent] Fix #{state.item_id}: {state.issue_title}",
                body=body,
                draft=True,
            )

            gate = ApprovalGate(project.autonomy)
            note = (
                "awaiting human review/merge"
                if gate.requires_human("merge")
                else "auto-merge path (not implemented yet)"
            )
            return {
                "coding": {
                    "change": change,
                    "files_written": written,
                    "pr_url": pr_url,
                    "note": note,
                }
            }
        finally:
            try:
                await asyncio.to_thread(ws.remove_worktree, wt_path)
            except Exception:  # noqa: BLE001 — cleanup is best-effort
                pass

    async def _code(self, worktree: Path, brief: str, plan: ImplementationPlan) -> CodeChange:
        targets = (plan.relevant_files + plan.new_files)[:_MAX_FILES]
        current = []
        for rel in targets:
            body = await asyncio.to_thread(code_intel.read_file, worktree, rel)
            current.append(f"### {rel}\n```\n{body or '(file does not exist yet)'}\n```")

        user = (
            f"## Work brief\n{brief}\n\n"
            f"## Implementation plan\n{plan.model_dump_json(indent=2)}\n\n"
            "## Current file contents\n" + ("\n\n".join(current) or "(none provided)") + "\n\n"
            "Produce the code change (full file contents for each edit)."
        )
        return await self.generate(CodeChange, system=_SYSTEM, user=user)


def _apply_change(worktree: Path, change: CodeChange) -> list[str]:
    """Write the edits into the worktree (sandboxed). Returns the written paths."""
    written: list[str] = []
    root = worktree.resolve()
    for edit in change.edits:
        target = (worktree / edit.path).resolve()
        if not str(target).startswith(str(root)):
            raise ValueError(f"edit path escapes worktree: {edit.path}")
        if edit.action == EditAction.modify and not target.exists():
            pass  # treat as create if the model mislabeled it
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(edit.content)
        written.append(edit.path)
    return written
