# Generated by Django 6.0.6 on 2026-06-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('config_name', models.CharField(help_text='Name of projects/<config_name>.yaml', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='house.client')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.IntegerField()),
                ('issue_title', models.CharField(blank=True, max_length=500)),
                ('branch', models.CharField(blank=True, max_length=300)),
                ('pr_url', models.URLField(blank=True)),
                ('stage', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('error', models.TextField(blank=True)),
                ('state', models.JSONField(default=dict, help_text='Full serialized WorkflowState')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='house.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
