"""Phase 1 build-team pipeline (plan §4a/§4c):

  issue → PM spec → Board sink (specs live here, NOT the PR)
        → worktree → Research/Spike (plan) → Dev/Coding (real edits) → commit code
        → push → PR (carries CODE) → merge ApprovalGate
        → cleanup worktree (unless --keep)

The PR now carries implementation, not the spec. Reviewer/Fixer (Phases 2–3) act on the PR.
"""

from __future__ import annotations

from .agents.coding_agent import apply_change, code
from .agents.pm_agent import build_spec
from .agents.research_agent import research
from .config import ProjectConfig, load_llm_settings
from .connectors.board import get_board
from .connectors.git_repo import RepoWorkspace
from .connectors.github import fetch_issue
from .connectors.pr import create_pr
from .gates import ApprovalGate
from .llm import LLMClient
from .state import Stage, Status, WorkflowState


def run_build(
    project: ProjectConfig, issue_number: int, keep_worktree: bool = False
) -> WorkflowState:
    state = WorkflowState(project=project.name, issue_number=issue_number)
    state.attempt_count += 1
    llm = LLMClient(load_llm_settings())
    repo = project.issues.source_repo

    # 1) issue → spec (PM)
    issue = fetch_issue(repo, issue_number)
    state.issue_title, state.issue_url = issue.title, issue.url
    state.record(Stage.spec, Status.in_progress, f"{repo}#{issue_number}")
    spec = build_spec(llm, repo, issue).parsed
    state.spec = spec
    state.record(Stage.spec, Status.ok, spec.epic.title)

    # 2) spec → Board sink (client oversight) — NOT the PR
    board = get_board(project.runtime_dir / "board")
    board_ref = board.publish_spec(issue_number, issue.url, spec)
    state.record(Stage.spec, Status.ok, f"board: {board_ref}")

    # 3) worktree off synced base
    ws = RepoWorkspace(project.work, project.runtime_dir / "worktrees")
    ws.ensure_upstream()
    base_ref = ws.sync_base()
    branch = ws.branch_name(issue_number, issue.title)
    state.branch = branch
    wt_path = ws.create_worktree(branch, base_ref)
    state.worktree_path = str(wt_path)

    try:
        # 4) Research/Spike → plan (read-only)
        state.record(Stage.research, Status.in_progress, "exploring repo")
        plan = research(llm, wt_path, issue.title, spec)
        state.record(
            Stage.research, Status.ok, f"{len(plan.relevant_files)} files, {len(plan.steps)} steps"
        )

        # 5) Dev/Coding → real edits → apply
        state.record(Stage.coding, Status.in_progress, "implementing")
        change = code(llm, wt_path, spec, plan)
        if not change.edits:
            state.record(Stage.coding, Status.error, "coding agent produced no edits")
            state.record(Stage.escalated, Status.error, "no implementation; needs human")
            return state
        written = apply_change(wt_path, change)
        sha = ws.commit_all(wt_path, f"agent: implement issue #{issue_number} — {issue.title}")
        state.record(Stage.coding, Status.ok, f"{len(written)} files @ {sha[:10]}")

        # 6) push + PR (CODE)
        ws.push_branch(wt_path, branch)
        body = (
            f"Implements {repo}#{issue_number} — {issue.url}\n\n"
            f"{change.summary}\n\n"
            f"**Files changed:** {', '.join(written)}\n\n"
            f"**Tests:** {change.tests_note or 'n/a'}\n\n"
            f"_Spec on board: `{board_ref}`. Generated by the loop engine build team._"
        )
        pr_url = create_pr(
            target_repo=project.work.target_repo,
            base=project.work.base_branch,
            head=branch,
            title=f"[agent] Fix #{issue_number}: {issue.title}",
            body=body,
            draft=True,
        )
        state.pr_url = pr_url
        state.record(Stage.pr, Status.ok, pr_url)

        # 7) merge gate
        gate = ApprovalGate(project.autonomy)
        if gate.requires_human("merge"):
            state.record(Stage.review, Status.pending, "awaiting human review/merge")
        else:
            state.record(Stage.review, Status.ok, "auto-merge path (not implemented yet)")
    finally:
        if not keep_worktree:
            try:
                ws.remove_worktree(wt_path)
            except Exception as exc:  # noqa: BLE001 — cleanup is best-effort
                state.record(state.stage, state.status, f"worktree cleanup failed: {exc}")

    return state
